{
 "title": "Amtron Sessions",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Wallbox",
    "label": "Wallbox",
    "query": "show tag values from amtron_status with key=\"DevName\""
   },
   {
    "name": "Name",
    "query": "show tag values from amtron_sessions with key=\"Name\""
   }
  ]
 },
 "panels": [
  {
   "title": "WB1 Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ChgState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=", "value": "wb1" }
     ]
    }
   ]
  },
  {
   "title": "WB1 Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ActPwr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=", "value": "wb1" }
     ]
    }
   ]
  },
  {
   "title": "WB2 Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ChgState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=", "value": "wb2" }
     ]
    }
   ]
  },
  {
   "title": "WB2 Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "targets": [
    {
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ActPwr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=", "value": "wb2" }
     ]
    }
   ]
  },
  {
   "title": "WB3 Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ChgState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=", "value": "wb3" }
     ]
    }
   ]
  },
  {
   "title": "WB3 Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "targets": [
    {
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ActPwr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=", "value": "wb3" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "description": "Total Number of chargesessions",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "amtron_sessions",
     "select": [
      [
       { "params": [ "ChgNrg" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=~", "value": "/^$Wallbox$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$Name$/" }
     ]
    }
   ]
  },
  {
   "title": "Wallbox Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Leistung ($tag_DevName)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DevName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "amtron_status",
     "select": [
      [
       { "params": [ "ActPwr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=~", "value": "/^$Wallbox$/" }
     ]
    }
   ]
  },
  {
   "title": "Summary",
   "type": "grafana-piechart-panel",
   "description": "Chargesession Energy Revenue per RFID Tag",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 4 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_Name ($tag_Uid)",
     "groupBy": [
      { "params": [ "Uid" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "DevName" ], "type": "tag" }
     ],
     "measurement": "amtron_sessions",
     "query": "select sum(ChgNrg) from (SELECT \"ChgNrg\"  / 1000 FROM \"amtron_sessions\" WHERE (\"DevName\" =~ /^$Wallbox$/ AND \"Name\" =~ /^$Name$/) AND $timeFilter GROUP BY \"Uid\", \"Name\", \"DevName\") GROUP BY \"Name\", \"Uid\"",
     "select": [
      [
       { "params": [ "ChgNrg" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=~", "value": "/^$Wallbox$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$Name$/" }
     ]
    }
   ]
  },
  {
   "title": "Totel Energy delivered",
   "type": "singlestat",
   "description": "Total amount of energy charged",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "format": "watth",
   "valueName": "first",
   "targets": [
    {
     "measurement": "amtron_sessions",
     "query": "SELECT sum(\"ChgNrg\") as CSUM FROM \"amtron_sessions\" WHERE $timeFilter GROUP BY \"url\"",
     "select": [
      [
       { "params": [ "ChgNrg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=~", "value": "/^$Wallbox$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$Name$/" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "table",
   "description": "Detailed Chargesession Listing",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Uid" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" }
     ],
     "measurement": "amtron_sessions",
     "select": [
      [
       { "params": [ "ChgNrg" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ],
      [
       { "params": [ "Stop" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ],
      [
       { "params": [ "DevName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "DevName", "operator": "=~", "value": "/^$Wallbox$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$Name$/" }
     ]
    }
   ]
  }
 ]
}